In [7]:
# Importiere die notwendigen Bibliotheken
import pandas as pd
from tabulate import tabulate
from IPython.display import display, HTML

# 1. Lese die CSV-Datei ein
# Ersetze 'sails_results.csv' durch den Pfad zu deiner CSV-Datei
df = pd.read_csv('sa_ls_results.csv')

sorted_df = df.sort_values(by='TotalProfit', ascending=False)
# 2. Formatiere die Tabelle mit Pandas Styling für die Anzeige in Jupyter Notebook
styled_df = sorted_df.style.format({
    'TotalProfit': '{:.0f}',   # Formatiere TotalProfit mit 2 Nachkommastellen
    'WaitingTime': '{:.0f}',   # Formatiere WaitingTime mit 2 Nachkommastellen
    'TotalTasks': '{:.0f}',   # Formatiere TotalTasks ohne Nachkommastellen
    'temp_decrease_factor': '{:.2f}',
    'min_temperature' : '{:.0e}'
})

# Zeige die formatierte Tabelle in Jupyter Notebook an
display(styled_df)

# 3. Zeige die Tabelle als ASCII-Tabelle mit 'tabulate' in der Konsole an
# Diese Ausgabe sieht in der Konsole oder im Terminal gut aus
table = tabulate(df, headers='keys', tablefmt='pretty', showindex=False)

#Sortiere die Tabelle nach der Spalte 'TotalProfit' absteigend